# Generated by Django 5.2.6 on 2025-10-03 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('socials', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceflightNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nasa_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('url', models.URLField()),
                ('image_url', models.URLField(blank=True)),
                ('news_site', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('featured', models.BooleanField(default=False)),
                ('launches', models.JSONField(default=list)),
                ('events', models.JSONField(default=list)),
                ('article_type', models.CharField(choices=[('article', 'Article'), ('blog', 'Blog'), ('report', 'Report')], default='article', max_length=20)),
            ],
            options={
                'verbose_name': 'Spaceflight News',
                'verbose_name_plural': 'Spaceflight News',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNewsPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_news_sites', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
