# Generated by Django 5.2.6 on 2025-10-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceflightnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsauthor',
            name='socials',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
