# Generated by Django 5.2.6 on 2025-10-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceflightnews', '0002_alter_newsauthor_socials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsauthor',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
