# Generated by Django 5.2.6 on 2025-10-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceflightnews', '0003_alter_newsauthor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceflightnews',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
