# Generated by Django 5.2.6 on 2025-10-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skymap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skymarker',
            name='catalog_number',
            field=models.CharField(blank=True, help_text='Catalog number (e.g., HIP 12345, M 31)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skymarker',
            name='designation',
            field=models.CharField(blank=True, help_text='Official designation (e.g., HD 12345, NGC 1234)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skymarker',
            name='object_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional Stellarium object properties'),
        ),
        migrations.AddField(
            model_name='skymarker',
            name='stellarium_type',
            field=models.CharField(blank=True, help_text='Raw Stellarium object type', max_length=100, null=True),
        ),
    ]
