# Generated by Django 5.2.6 on 2025-10-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NASAMediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nasa_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('center', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.JSONField(default=list)),
                ('photographer', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('preview_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('original_url', models.URLField(blank=True)),
                ('description_508', models.TextField(blank=True)),
                ('secondary_creator', models.CharField(blank=True, max_length=255)),
                ('album', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'NASA Media Item',
                'verbose_name_plural': 'NASA Media Items',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('int_designator', models.CharField(blank=True, max_length=20)),
                ('orbit_type', models.CharField(blank=True, choices=[('LEO', 'Low Earth Orbit'), ('MEO', 'Medium Earth Orbit'), ('GEO', 'Geostationary Orbit'), ('HEO', 'Highly Elliptical Orbit'), ('DEEP', 'Deep Space')], max_length=10)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('decay_date', models.DateField(blank=True, null=True)),
                ('tle_line1', models.CharField(max_length=100)),
                ('tle_line2', models.CharField(max_length=100)),
                ('tle_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Satellite',
                'verbose_name_plural': 'Satellites',
                'ordering': ['name'],
            },
        ),
    ]
