# Generated by Django 5.2.6 on 2025-10-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_api', '0002_nasamediaitem_satellite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaveditem',
            name='item_type',
            field=models.CharField(choices=[('apod', 'APOD'), ('neo', 'Near Earth Object'), ('mars_photo', 'Mars Rover Photo'), ('epic', 'EPIC Image'), ('exoplanet', 'Exoplanet'), ('space_weather', 'Space Weather Event'), ('natural_event', 'Natural Event'), ('space_event', 'Space Event')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usertrackedobject',
            name='object_type',
            field=models.CharField(choices=[('apod', 'APOD'), ('neo', 'Near Earth Object'), ('mars_photo', 'Mars Rover Photo'), ('epic', 'EPIC Image'), ('exoplanet', 'Exoplanet'), ('space_weather', 'Space Weather Event'), ('natural_event', 'Natural Event'), ('space_event', 'Space Event')], max_length=20),
        ),
        migrations.CreateModel(
            name='SpaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nasa_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('ECLIPSE_SOLAR', 'Solar Eclipse'), ('ECLIPSE_LUNAR', 'Lunar Eclipse'), ('SUPERMOON', 'Supermoon'), ('METEOR_SHOWER', 'Meteor Shower'), ('PLANETARY_ALIGNMENT', 'Planetary Alignment'), ('CONJUNCTION', 'Planetary Conjunction'), ('COMET', 'Comet Appearance'), ('TRANSIT', 'Planet Transit'), ('OCCULTATION', 'Occultation'), ('EQUINOX', 'Equinox'), ('SOLSTICE', 'Solstice'), ('LAUNCH', 'Space Launch'), ('MISSION', 'Space Mission Event'), ('OTHER', 'Other Astronomical Event')], max_length=30)),
                ('event_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('GLOBAL', 'Global'), ('NORTHERN_HEMISPHERE', 'Northern Hemisphere'), ('SOUTHERN_HEMISPHERE', 'Southern Hemisphere'), ('PARTIAL', 'Partial Visibility'), ('LOCAL', 'Local/Regional')], default='GLOBAL', max_length=30)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('peak_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_upcoming', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Space Event',
                'verbose_name_plural': 'Space Events',
                'ordering': ['event_date'],
                'indexes': [models.Index(fields=['event_date'], name='nasa_api_sp_event_d_24a256_idx'), models.Index(fields=['event_type'], name='nasa_api_sp_event_t_9774e3_idx'), models.Index(fields=['is_featured'], name='nasa_api_sp_is_feat_ca5b20_idx'), models.Index(fields=['is_upcoming'], name='nasa_api_sp_is_upco_00f3e6_idx')],
            },
        ),
    ]
