# Generated by Django 5.2.6 on 2025-10-07 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murphai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='murphchat',
            old_name='question',
            new_name='prompt',
        ),
        migrations.RenameField(
            model_name='murphchat',
            old_name='answer',
            new_name='response',
        ),
        migrations.RenameField(
            model_name='murphchat',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterModelTable(
            name='murphchat',
            table='murphai_murphchat',
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murph_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'murphai_conversation',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='murphai.conversation')),
            ],
            options={
                'db_table': 'murphai_message',
                'ordering': ['timestamp'],
            },
        ),
    ]
