# Generated by Django 5.2.6 on 2025-10-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacexlaunch',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spacexlaunch',
            name='fairings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
