# Generated by Django 5.2.6 on 2025-10-20 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercontent_usercollection_userjournal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=200, unique=True)),
                ('source', models.CharField(choices=[('nasa_ads', 'NASA ADS'), ('arxiv', 'arXiv'), ('crossref', 'Crossref')], max_length=50)),
                ('title', models.CharField(max_length=1000)),
                ('authors', models.TextField()),
                ('abstract', models.TextField()),
                ('published_date', models.DateField()),
                ('journal', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=200, null=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('citation_count', models.IntegerField(default=0)),
                ('save_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'research_papers',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['source', 'published_date'], name='research_pa_source_c22e94_idx'), models.Index(fields=['paper_id'], name='research_pa_paper_i_b9d673_idx'), models.Index(fields=['published_date'], name='research_pa_publish_bed1e3_idx'), models.Index(fields=['save_count'], name='research_pa_save_co_a76bae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('journal', 'Journal Entry'), ('paper', 'Research Paper'), ('event', 'Event')], max_length=30)),
                ('target_id', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='comments_target__71256e_idx'), models.Index(fields=['user'], name='comments_user_id_8613ff_idx'), models.Index(fields=['parent'], name='comments_parent__9f8798_idx')],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('journal', 'Journal Entry'), ('paper', 'Research Paper'), ('comment', 'Comment')], max_length=30)),
                ('target_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='likes_target__37f167_idx'), models.Index(fields=['user'], name='likes_user_id_4c8dad_idx')],
                'unique_together': {('user', 'target_type', 'target_id')},
            },
        ),
        migrations.CreateModel(
            name='UserFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_followers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower'], name='user_follow_followe_a9075a_idx'), models.Index(fields=['following'], name='user_follow_followi_1e25dd_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='UserPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_favorite', models.BooleanField(default=False)),
                ('read_status', models.CharField(choices=[('unread', 'Unread'), ('reading', 'Reading'), ('read', 'Read')], default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='users.researchpaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_papers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_favorite'], name='user_papers_user_id_8ac905_idx'), models.Index(fields=['user', 'read_status'], name='user_papers_user_id_02c602_idx'), models.Index(fields=['created_at'], name='user_papers_created_ed82e0_idx')],
                'unique_together': {('user', 'paper')},
            },
        ),
    ]
