# Generated by Django 5.2.6 on 2025-10-21 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_researchpaper_comment_like_userfollower_userpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('unread_count_user1', models.IntegerField(default=0)),
                ('unread_count_user2', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads_1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads_2', to=settings.AUTH_USER_MODEL)),
                ('last_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_of_thread', to='users.usermessage')),
            ],
            options={
                'db_table': 'message_threads',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['sender', 'recipient'], name='user_messag_sender__2984d1_idx'),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['recipient', 'is_read'], name='user_messag_recipie_217221_idx'),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['created_at'], name='user_messag_created_3626aa_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['user1', 'last_activity'], name='message_thr_user1_i_c6c55a_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['user2', 'last_activity'], name='message_thr_user2_i_e78209_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagethread',
            unique_together={('user1', 'user2')},
        ),
    ]
