# Generated by Django 5.2.6 on 2025-10-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermessage_messagethread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='content_type',
            field=models.CharField(choices=[('apod', 'Astronomy Picture of the Day'), ('mars_photo', 'Mars Rover Photo'), ('epic', 'Earth EPIC Image'), ('neo', 'Near-Earth Object'), ('exoplanet', 'Exoplanet'), ('space_weather', 'Space Weather Event'), ('news', 'Space News Article'), ('celestial', 'Celestial Object (Skymap)'), ('event', 'Cosmic Event'), ('nasa_image', 'NASA Image Library'), ('space_launch', 'Space Launch'), ('gallery_image', 'Gallery Image')], max_length=50),
        ),
    ]
